### ISSUE TITLE
RNGModifier breaks the mod options menu

### ISSUE THREAD

**Issue by nullifiedcatt** [DrNewbie/RNGModifier#21]
Im deleted all mods, but the mod menu are still empty. IF I delete RNGModifier, the mod options is back. Whats wrong?

**Comment by Berk-Rider** [comment]
There doesn't seem to have anything wrong with the mod. I just downloaded and installed the version from here and my mods menu are showing just fine.
Perhaps it's not RNGModifier but one of your mods that's conflicting with it and causing the issue?
3 possible solutions that I know:
1-
Delete the RNGModifier you have and download it from here, then if blt asks for an update you do it (probably won't ask since it's already up to date) install it and try again.
2-
Move all your mods to a different folder and install them again 1 by 1, open the game and check the mods menu, keep doing it untill you find the one causing the issue.
3-
Check the blt menu and see if your mods are not disabled. I ran into a issue like that before were most of my mods got disabled for some reason
Maybe Dr_Newbie can give you a better help.

**Comment by Kolop98** [comment]
I'm having the same issue. 
1-Attempted, multiple times. No update prompt
2-Attempted, as well as leaving each mod installed and disabling them. Neither worked.
3-Not disabled. When disabled and re-nabled, issue persists.

When this mod is actively installed/enabled the mod options menu is empty except for a language selector.

**Comment by Berk-Rider** [comment]
Strange... I just recheck the code again and I'm (just like bain would say) 99% sure the mod is working just fine, otherwise I would get the same issue with my game.
I made a new pull request including new options for boiling point, don't know if it gonna have anything to do with the problem but maybe if you wait for Dr_Newbie to aprove it there's a chance that the issue gets fixed too once you update it.
Also, probably obvious that it'll be a "yes", but are you using SUPERBLT? In case you're using normalblt, update it to super, should fix it too.

**Comment by Kolop98** [comment]
Yes I am using SuperBLT. I just tried a fresh install of SuperBLT as well as RNGModifier and the issue still persisted. Good luck with this, lol!

**Comment by Berk-Rider** [comment]
ok I think I just found a little error, hopefully it's whats causing the issue and you guys can fix it doing the following:
1- go to hooks/heists/fish.lua
2- go to either line 48 or 49 and delete it (I hit the ENTER key twice on that line now there's 2 blanks spaces where should have only 1)
3- save and test it ingame

I'll keep checking for more fails here but hopefully this is what's causing all the fuzz

**Comment by Kolop98** [comment]
I'm afraid that didn't fix the issue. It did however seem to prompt BLT to report that an update is available for the mod, which fails every time I attempted to update. Re-adding the space to the code, of course, did not fix the update issues. A fresh install of RNGModifier did not get rid of the update prompt either, and it still failed to update. Weirdly enough, after removing the space on line 48 in the fresh install the update no longer failed. The update did not fix the mod options.

**Comment by Berk-Rider** [comment]
I didn't updated the mod, that only Dr_Newbie has the power to do so, I just made a pull request for an adjust
once you erased line 48/49 you can't update the mod because it'll put the empty line back again, you gotta test the mod even with it asking to be updated

**Comment by Berk-Rider** [comment]
try erasing line 48/49 again and check the options without updating the mod
if that doesn't work, then go to Base.lua and put "--" (without quotes) on the lines that says "spa" and "fish", so they look like this:
--fish
--spa
if they get green then yo udid it right, test the game, and again, don't update the mod
this will block the options for the last 2 heist updates I made

**Comment by Berk-Rider** [comment]
if even so the bug persists, then I really don't know what to do
I can send you my mod version if you want but even though it's working for me I can't promisse it'll work for you

**Comment by Berk-Rider** [comment]
http://www.mediafire.com/file/a5x47vg1pdvmwqg/RNGModifier.zip/file

this is my own version of the mod
again, I can't promisse it'll work, as it's the same version of github except by the fact it's a WIP with boiling point options (which are just waiting to be accepted on pull request)

**Comment by Kolop98** [comment]
Guess I wasn't too clear, sorry about that. I tested it before attempting to update and the issue still persisted. I just attempted both marking fish/spa as comments(green) and replacing my version with yours, still no luck

**Comment by Berk-Rider** [comment]
Then I really got no clue of what's happening, for dr to accept my pull request I guess he at least tested it by himself before merging my changes/additions with his mod.
Gotta wait for an official release of him. Hopefully it'll involve a fix.

**Comment by Berk-Rider** [comment]
Ok guys, my friend agreed to test it for me, his game was uninstalled so he had to install it again to help me, which means it was a clean install of the game
After he instaled superblt (iphlpapi version) and only rngmodifier he said the menus were showing up and working just fine, he even told me the options he was seeing.

My conclusion is that the problem is with your game and/or your mods and not rngmodifier itself. :\

**Comment by Foxy163rus** [comment]
I have the same problem. I am 100% sure that the problem is incompatibility with other mods. If you find with which mod the rngmodifier conflicts with, please report it

**Comment by Kolop98** [comment]
I’m going to test in this in the morning, but I have a sneaking suspicion that the issue is a/any custom heists. None of my mods are conflicting and I have a ton of custom heists installed and considering the nature of the mod and how the menu options are laid out in the images I’m guessing the mods breaking trying to include those heists?

**Comment by Foxy163rus** [comment]
Well, I can say that rngmodifier is not compatible with the mod **[Big Oil] Engine Helper**. If the creator of rngmodifier is reading this, please try to fix it so the mods work together. :yum:

**Comment by Kolop98** [comment]
Well I didn't even get to test the custom heist issue. I re-installed the mod this morning and it's working fine? Really confused! Custom heists are fine I guess. Working for me now!

**Comment by nullifiedcatt** [comment]
I have now tried to check the functionality of the mod with the IPHLPAPI version. I wrote above that the mods are removed ALL. SuperBLT and RNGModifier alone. I'll write the news.

**Comment by nullifiedcatt** [comment]
После установки RNGModifier и SuperBLT(IPHPAPI.dll), а также удалении папки Maps опция появилась и стала работоспособной.
